### ISSUE TITLE
extra code that will break the decoding piece

### ISSUE THREAD

**Issue by fireole** [neosmart/UrlBase64#1]
case 2:
                    chars.Add('=');    <== remove this one
                    chars.AddRange(TwoPads);

**Comment by mqudsi** [comment]
Thank you very much for catching this.

**Comment by mqudsi** [comment]
UrlBase64 has been updated to version 0.1.1 on NuGet, which contains this fix: https://www.nuget.org/packages/UrlBase64/0.1.1
