### ISSUE TITLE
Decode behavior has changed unexpectedly

### ISSUE THREAD

**Issue by BrandonDusseau** [neosmart/UrlBase64#7]
We attempted to upgrade UrlBase64 from 0.1.2 to 1.0.1, but the decoding is not consistent with the previous version. I consider this a bug and an undocumented breaking change.

Here are some test cases that all previously passed:

### Correct
Input
`SGVsbG8sIHdvcmxk`
Expected
`[48 65 6C 6C 6F 2C 20 77 6F 72 6C 64]`
Actual
`[48 65 6C 6C 6F 2C 20 77 6F 72 6C 64]`

### Incorrect - a different decode result has been produced
Input
`Q29udGFpbnMgYSBwbHVzIMOlw6bDn+KApuKIgsuaxpLiiIY=`
Expected
`[43 6F 6E 74 61 69 6E 73 20 61 20 70 6C 75 73 20 C3 A5 C3 A6 C3 9F *E2* 80 A6 E2 88 82 CB 9A C6 92 E2 88 86]`
Actual
`[43 6F 6E 74 61 69 6E 73 20 61 20 70 6C 75 73 20 C3 A5 C3 A6 C3 9F *F2* 80 A6 E2 88 82 CB 9A C6 92 E2 88 86]`

### Correct
Input
`Q29udGFpbnMgYSBwbHVzIMOlw6bDn-KApuKIgsuaxpLiiIY`
Expected
`[43 6F 6E 74 61 69 6E 73 20 61 20 70 6C 75 73 20 C3 A5 C3 A6 C3 9F E2 80 A6 E2 88 82 CB 9A C6 92 E2 88 86]`
Actual
`[43 6F 6E 74 61 69 6E 73 20 61 20 70 6C 75 73 20 C3 A5 C3 A6 C3 9F E2 80 A6 E2 88 82 CB 9A C6 92 E2 88 86]`

### Incorrect - a different decode result has been produced
Input
`Q29udGFpbnMgYSBzbGFzaCDDuOKImsucw5/iiILiiJrLmsOn4oiC4omkw58=`
Expected
`[43 6F 6E 74 61 69 6E 73 20 61 20 73 6C 61 73 68 20 C3 B8 E2 88 9A CB 9C C3 *9F* E2 88 82 E2 88 9A CB 9A C3 A7 E2 88 82 E2 89 A4 C3 9F]`
Actual
`[43 6F 6E 74 61 69 6E 73 20 61 20 73 6C 61 73 68 20 C3 B8 E2 88 9A CB 9C C3 *BF* E2 88 82 E2 88 9A CB 9A C3 A7 E2 88 82 E2 89 A4 C3 9F]`

### Correct
Input
`Q29udGFpbnMgYSBzbGFzaCDDuOKImsucw5_iiILiiJrLmsOn4oiC4omkw58`
Expected
`[43 6F 6E 74 61 69 6E 73 20 61 20 73 6C 61 73 68 20 C3 B8 E2 88 9A CB 9C C3 9F E2 88 82 E2 88 9A CB 9A C3 A7 E2 88 82 E2 89 A4 C3 9F]`
Actual
`[43 6F 6E 74 61 69 6E 73 20 61 20 73 6C 61 73 68 20 C3 B8 E2 88 9A CB 9C C3 9F E2 88 82 E2 88 9A CB 9A C3 A7 E2 88 82 E2 89 A4 C3 9F]`

### Correct
Input
empty string
Expected
`[]`
Actual
`[]`

### Incorrect - this should not be able to be decoded
Input
`Invalid!`
Expected
FormatException thrown
Actual
`[22 7B DA 96 27 FF]`

The method under test is `UrlBase64.Decode()`.

With no release notes between package versions, it's not easy to see that this breaking change has occurred. We'll be downgrading back to 0.1.2 for now because it is critical that our decoded values remain consistent.

**Comment by mqudsi** [comment]
Hi there,

> With no release notes between package versions, it's not easy to see that this breaking change has occurred.

That's because there isn't supposed to be a change. This looks like a regression!

**Comment by mqudsi** [comment]
I see the issue now, you are expecting `UrlBase64.Decode(Base64.Encode(foo)) == foo` for all values of `foo`? i.e. decoding non-url-safe base64 with the url-safe base64 decode feature? That wasn't a use case we were accounting for though a) I can see why it previously worked, b) I can also see why you might want it.

**Comment by mqudsi** [comment]
I've uploaded version `2.0-preview2` to nuget that should address these regressions. Can you please let me know if it meets your needs?

**Comment by BrandonDusseau** [comment]
I've just tested using the preview version. Our tests are now all passing!
We do appreciate you jumping on this problem.

**Comment by mqudsi** [comment]
No problem. Thanks for reporting the issue and for  helping with the preview release!
